# docker-compose.yml
version: "3"
services:
  app:
    image: node:12
    user: "node"
    working_dir: /home/node/app
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://user:pass@postgres:5432/db
      NODE_ENV: development
      PORT: 3002
    ports:
      - "3002:3002"
    command: tail -f /dev/null
    volumes:
      - ./:/home/node/app

  postgres:
    image: postgres:10.4
    ports:
      - "35432:5432"
    volumes:
      - ./db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: db